FROM debian

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y vim ctags curl git tmux

RUN curl https://raw.githubusercontent.com/thesheff17/vim/master/vimrc  --output /root/.vimrc

RUN git clone https://github.com/torvalds/linux.git && \
    cd linux && \
    ctags -R .

CMD ["/usr/bin/tmux"]
